backend = "glx";

blur = {
  method = "dual_kawase";
  strength = 8;
  deviation = 0.0;
  kernel = "11x11gaussian";
  background = false;
};

blur-background-exclude = [
  "class_g = 'slop'",
  "_GTK_FRAME_EXTENTS@"
];

# Focus differentiation
active-opacity = 0.8;
inactive-opacity = 0.6;
inactive-dim = 0.08;

# Exclude picom's own transparency rules from system bars
opacity-rule = [
  "100:class_g = 'Polybar'",
  "100:class_g = 'firefox-esr'",
  "100:class_g = 'Firefox-esr'",
  "100:class_g = 'brave-browser'",
  "100:class_g = 'Brave-browser'",
  "100:class_g = 'google-chrome'",
  "100:class_g = 'Google-chrome'",
  "100:class_g = 'chromium-browser'",
  "100:class_g = 'Chromium-browser'",
  "100:class_g = 'Comet'",
  "100:class_g = 'comet'"
];

# No shadows
shadow = false;
